### ISSUE TITLE
HTTP header Content-Type without charset in PHP 5.6

### ISSUE THREAD

**Issue by stekycz** [nette/http#29]
When you want to set header `Content-Type` without `charset` attribute for type `text/*` then PHP 5.6 adds default charset into the header for you. However it could bring some problems in some cases (back compatibility for example). It is caused by usage of [function sapi_apply_default_charset](https://github.com/php/php-src/blob/efe9cc3a86a769f1ac3d16f4b12f5e83053c6822/main/SAPI.c#L375-L394).

Working solution follows
```php
$default_charset = ini_get('default_charset');
ini_set('default_charset', NULL);
// set header
ini_set('default_charset', $default_charset);
```

I am not sure if it should be solved by Nette. However Nette supports passing `charset` as second parameter to method `IResponse::setContentType` so it could. What do you think?

**Comment by dg** [comment]
The default_charset is like a cancer, since 5.6 it is everywhere: [htmlspecialchars](http://php.net/htmlspecialchars), html_entity_decode, etc. Now you have to always call htmlspecialchars with 3rd argument, because otherwise function is not deterministic :-(

The proposed solution `setContentType($type, NULL)` is magic, usable only for a few people who know what's going on. 

I thought about it for a long time and I suggest: let it be.

**Comment by stekycz** [comment]
@dg Hmm, a lot of changes I can see. I could prepare gist instead of this pull. The gist could be mentioned in Nette doc. What about that?

**Comment by dg** [comment]
Notice like *PHP is some cases appends ini_get('default_charset')* is enough, isn't?

**Comment by stekycz** [comment]
I guess...

**Comment by JanTvrdik** [comment]
> Now you have to always call htmlspecialchars with 3rd argument

Why? We can make a strict requirement that Nette requires `default_charset` to be set to UTF-8. Why would that be a problem?

**Comment by dg** [comment]
I am not talking about Nette, but about fundamentally bad decision.

**Comment by JanTvrdik** [comment]
So you think that the previous state (some functions depending on one ini setting, some functions depending on entirely different ini setting, some functions with a default value independent of ini settings) was better?

**Comment by dg** [comment]
Yes previous state was definitely better.

**Comment by JanTvrdik** [comment]
Previously PHP behavior were affected by the following ini settings:

~~~php
php.input_encoding
php.internal_encoding
php.output_encoding
iconv.input_encoding (Default: php.input_encoding)
iconv.internal_encoding (Default: php.internal_encoding)
iconv.output_encoding (Default: php.output_encoding)
mbstring.http_input (Default: php.input_encoding)
mbstring.internal_encoding (Default: php.internal_encoding)
mbstring.http_output (Default: php.output_encoding)
~~~

Since PHP 7 (PHP 5.6 only deprecated the previous settings) there will be only one ini setting – `default_charset`. You need to set this properly and you are good to go.

**Comment by dg** [comment]
Why are you talking about it?

**Comment by JanTvrdik** [comment]
No good reasons, really. I was just a bit surprised that you consider the previous state better.

**Comment by dg** [comment]
Because I don't like global variables. Thats all. I had to used last parameter in all `iconv_*` and `mb_*` and `http_build_query` functions before, now I have to do it for `htmlspecialchars` and other functions. Is it better? Absolutely no.
