### ISSUE TITLE
\Nette\Http\Url ignore user and password for http and https links

### ISSUE THREAD

**Issue by integer** [nette/http#63]
What is the reason for this line of code https://github.com/nette/http/blob/master/src/Http/Url.php#L363 ? What is the main difference between `http` and `https` and other schemas?

Expected behavior: generate link with user and password for every schema if user and password are set.

**Comment by JanTvrdik** [comment]
My guess is that passing username+password in URL is considered insecure.

**Comment by integer** [comment]
Ok, but why it is OK for ftp, but insecure for http?

Odeslané z telefonu HTC

----- Reply message -----
Od: "Jan Tvrdík" <notifications@github.com>
Komu: "nette/http" <http@noreply.github.com>
Kopie: "Pavel Kácha" <int@integerovo.info>
Předmět: [http] \Nette\Http\Url ignore user and password for http and https links (#63)
Datum: st, 6. 10, 2015 22:00
My guess is that passing username+password in URL is considered insecure. 

&mdash;

**Comment by dg** [comment]
For asking use forum please.

http://forum.nette.org/cs/748-jmeno-a-heslo-v-adresach

**Comment by artyuum** [comment]
@dg sure, let's talk in a forum where the language is not even english ,this will certainly help the others who has the same issue...

**Comment by milo** [comment]
@artyuum Why do you suppose, that "the others" are incompetent idiods? It is not nice from you. I would suppose, that the others can always write: "Hi, I tried to Google-translate the forum post, but still don't undestand. Could someone white here result in english please?"

And someone can write: "Sure. There is written, that the HTTP and HTTPS used to behave in the same way as other protocols. But showed up, that it was not secure. And because we didn't find a use case, we dropped user and password from these protocols. What is your use case?"

**Comment by artyuum** [comment]
@milo My bad, I just found out that the forum offers two languages :

- Česky
- English

I didn't see it earlier.
Anyway, I've never called anyone who has the same issue : incompetent "idiods". I wasn't trying to be rude to anyone, I was just a little mad because for an opensource project you shouldn't redirect anyone who asks a question in English, to a forum where the language is not even English, that was before I realize that the forum has an "English section'.
